user  nginx;
worker_processes  1;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;
events {
    worker_connections  1024;
}
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    gzip        off;
    keepalive_timeout  65;

    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name _;
        root /app/publish;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
            autoindex on;
        }

        add_header Accept-Ranges bytes always;

        access_log /var/log/nginx/access.log;
        error_log  /var/log/nginx/error.log;
    }
}
